setup scripts: update redhat setup script.
MentorEmbedded/meta-sokol-flex pull request #122
Opened 2023-05-09 07:51 UTC by ArsalanSaleemGhuman

The python's setuptool package is already installed
    in RedHat. Removed explicitly installing the setuptool
    package in setup-rh script.

    JIRA: SB-22045

    Signed-off-by: Arsalan Saleem <arsalan_saleem@mentor.com>

2023-05-09 07:55 UTC, Noor-Ahsan commented
@ArsalanSaleemGhuman can you also share the evidance that this package is already there or in Jira and point reviewer there

2023-05-09 08:05 UTC, ArsalanSaleemGhuman commented
@Noor-Ahsan ,
I have already added the information on JIRA ticket. See image below.
![image](https://user-images.githubusercontent.com/26869858/237033819-991aca0a-e77d-4a09-8087-bc1eeb8700ae.png)

2023-05-09 08:21 UTC, aarslan7 approved these changes

2023-05-09 09:46 UTC, abelal requested changes
The commit title should be
```
setup-rh: install/remove <package-name>
```

just saying "update" is way too generic. Also I think a more appropriate way would be to explicitly install the python3-setuptools (or whatever the package name is for RhEL) now that we know there's a dependency.

2023-05-09 10:00 UTC, ArsalanSaleemGhuman commented
> The commit title should be
> 
> ```
> setup-rh: install/remove <package-name>
> ```
> 
> just saying "update" is way too generic. Also I think a more appropriate way would be to explicitly install the python3-setuptools (or whatever the package name is for RhEL) now that we know there's a dependency.

sure let me add changes to install the package.

2023-05-09 12:21 UTC, abelal commented
@ArsalanSaleemGhuman why do we have 2 commits here now? I don't think the first one's needed. Also have you confirmed that the package name is "python3-setuptools" for RHEL?

2023-05-09 12:22 UTC, abelal commented
@ArsalanSaleemGhuman why do we have 2 commits here now? I don't think the first one's needed. Also have you confirmed that the package name is "python3-setuptools" for RHEL?

2023-05-10 08:22 UTC, ArsalanSaleemGhuman commented
@abelal  i have squashed the commits.

2023-05-10 10:16 UTC, abelal approved these changes

2023-05-10 10:17 UTC, merged

2023-05-10 10:20 UTC, abelal commented
> > @ArsalanSaleemGhuman why do we have 2 commits here now? I don't think the first one's needed. Also have you confirmed that the package name is "python3-setuptools" for RHEL?
> 
> Does it matter how many commits are there? Don't we squash and merge ?
> 
> Yes i have verified installing the python3-setuptools on RedHat.

@aarslan7 we merge as-is with an additional merge commit i.e. we don't squash and merge.